### ISSUE TITLE
Error while using Notification Listener

### ISSUE THREAD

**Issue by GarryLai** [iamfarhad/LaravelRabbitMQ#1]
**Version(s) affected**: 0.0.5

**Description**
Error while using Notification Listener

**How to reproduce**
Create a Notification Listener and send notification

**Possible Solution**

**Additional context**

> iamfarhad\LaravelRabbitMQ\RabbitQueue::publishProperties(): Argument #1 ($queue) must be of type string, null given, called in /var/www/dev/vendor/iamfarhad/laravel-rabbitmq/src/RabbitQueue.php on line 67 {"userId":1,"exception":"[object] (TypeError(code: 0): iamfarhad\\LaravelRabbitMQ\\RabbitQueue::publishProperties(): Argument #1 ($queue) must be of type string, null given, called in /var/www/dev/vendor/iamfarhad/laravel-rabbitmq/src/RabbitQueue.php on line 67 at /var/www/dev/vendor/iamfarhad/laravel-rabbitmq/src/RabbitQueue.php:403)

**Comment by iamfarhad** [comment]
> **Version(s) affected**: 0.0.5
> 
> **Description** Error while using Notification Listener
> 
> **How to reproduce** Create a Notification Listener and send notification
> 
> **Possible Solution**
> 
> **Additional context**
> 
> > iamfarhad\LaravelRabbitMQ\RabbitQueue::publishProperties(): Argument #1 ($queue) must be of type string, null given, called in /var/www/dev/vendor/iamfarhad/laravel-rabbitmq/src/RabbitQueue.php on line 67 {"userId":1,"exception":"[object] (TypeError(code: 0): iamfarhad\LaravelRabbitMQ\RabbitQueue::publishProperties(): Argument #1 ($queue) must be of type string, null given, called in /var/www/dev/vendor/iamfarhad/laravel-rabbitmq/src/RabbitQueue.php on line 67 at /var/www/dev/vendor/iamfarhad/laravel-rabbitmq/src/RabbitQueue.php:403)

Fixed

**Comment by GarryLai** [comment]
Not working

> iamfarhad\LaravelRabbitMQ\RabbitQueue::publishProperties(): Argument #1 ($queue) must be of type string, null given, called in /var/www/dev/vendor/iamfarhad/laravel-rabbitmq/src/RabbitQueue.php on line 67 {"userId":1,"exception":"[object] (TypeError(code: 0): iamfarhad\\LaravelRabbitMQ\\RabbitQueue::publishProperties(): Argument #1 ($queue) must be of type string, null given, called in /var/www/dev/vendor/iamfarhad/laravel-rabbitmq/src/RabbitQueue.php on line 67 at /var/www/dev/vendor/iamfarhad/laravel-rabbitmq/src/RabbitQueue.php:403)

**Comment by iamfarhad** [comment]
> Not working
> 
> > iamfarhad\LaravelRabbitMQ\RabbitQueue::publishProperties(): Argument #1 ($queue) must be of type string, null given, called in /var/www/dev/vendor/iamfarhad/laravel-rabbitmq/src/RabbitQueue.php on line 67 {"userId":1,"exception":"[object] (TypeError(code: 0): iamfarhad\LaravelRabbitMQ\RabbitQueue::publishProperties(): Argument #1 ($queue) must be of type string, null given, called in /var/www/dev/vendor/iamfarhad/laravel-rabbitmq/src/RabbitQueue.php on line 67 at /var/www/dev/vendor/iamfarhad/laravel-rabbitmq/src/RabbitQueue.php:403)

Update composer now, fixed

**Comment by GarryLai** [comment]
0.0.7 still not working. The message does not send out to RabbitMQ. Please make sure you test it before release.
